apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-eugene-food-scene-deployment
  namespace: eugene-food-scene-stage
  labels:
    app: eugene-food-scene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eugene-food-scene
  template:
    metadata:
      labels:
        app: eugene-food-scene
    spec:
      containers:
        - name: web-server
          image: codegold79/eugene-food-scene:1.0.2
          resources:
            limits:
              cpu: 0.25
              memory: 250Mi
            requests:
              cpu: 0.25
              memory: 250Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
