apiVersion: apps/v1
kind: Deployment
metadata:
  name: eugene-food-scene-deployment
  namespace: eugene-food-scene-prod
  labels:
    app: eugene-food-scene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eugene-food-scene
  template:
    metadata:
      labels:
        app: eugene-food-scene
    spec:
      containers:
        - name: web-server
          image: mvpstudio/eugene-food-scene:June14b
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
            requests:
              cpu: 0.5
              memory: 500Mi
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
